# Generated by Django 5.0.1 on 2024-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jassim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('S_name', models.CharField(max_length=10)),
                ('choice', models.CharField(choices=[('phone', 'phone'), ('coputer', 'coputer'), ('family', 'family'), ('love', 'love')], max_length=10)),
                ('emil', models.CharField(max_length=20)),
            ],
        ),
    ]
