# Generated by Django 5.0.1 on 2024-01-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='One_to_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
    ]
