# Generated by Django 5.0.1 on 2024-01-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourename', models.CharField(max_length=50)),
                ('yournumber', models.IntegerField()),
                ('namethedoctor', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
