# Generated by Django 5.0.1 on 2024-01-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_data_hospital_manage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_manage',
            old_name='namethedoctor',
            new_name='name_the_doctor',
        ),
        migrations.RenameField(
            model_name='hospital_manage',
            old_name='yourename',
            new_name='your_ename',
        ),
        migrations.RenameField(
            model_name='hospital_manage',
            old_name='yournumber',
            new_name='your_number',
        ),
    ]
