# Generated by Django 5.0.1 on 2024-01-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_rename_namethedoctor_hospital_manage_name_the_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_manage',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='hospital_manage',
            old_name='name_the_doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='hospital_manage',
            old_name='your_ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hospital_manage',
            old_name='your_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='hospital_manage',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
