# Generated by Django 5.0.1 on 2024-01-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_rename_name_hospital_manage_name1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital_manage',
            new_name='LOGIN',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Jassim',
        ),
        migrations.RemoveField(
            model_name='username',
            name='video',
        ),
        migrations.RemoveField(
            model_name='one_to_many',
            name='students',
        ),
        migrations.RemoveField(
            model_name='one_to_on',
            name='one',
        ),
        migrations.DeleteModel(
            name='Many_to_many',
        ),
        migrations.DeleteModel(
            name='Username',
        ),
        migrations.DeleteModel(
            name='One_to_many',
        ),
        migrations.DeleteModel(
            name='One_to_on',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
